<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <!-- ORDDirectory  -->
    <ORD>D:\Softwares\Civil Engineering\Bentley\OpenRoadsDesigner</ORD>
  </PropertyGroup>
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{C792745B-E212-4FAC-84BF-CCA3F0120702}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>ManagedSDKExample</RootNamespace>
    <AssemblyName>ManagedSDKExample</AssemblyName>
    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <TargetFrameworkProfile />
    <ReferencePath>$(ORD)</ReferencePath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\bin\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <PlatformTarget>x64</PlatformTarget>
    <DocumentationFile>..\bin\ManagedSDKExample.XML</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>$(ORD)\mdlapps</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Bentley.CifNET.GeometryModel.SDK.4.0">
      <HintPath>$(ORD)\Cif\Bentley.CifNET.GeometryModel.SDK.4.0.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Bentley.CifNET.GeometryModel.SDK.Edit.4.0">
      <Private>false</Private>
      <HintPath>$(ORD)\Cif\Bentley.CifNET.GeometryModel.SDK.Edit.4.0.dll</HintPath>
    </Reference>
    <Reference Include="Bentley.CifNET.LinearGeometry.4.0">
      <Private>false</Private>
      <HintPath>$(ORD)\Cif\Bentley.CifNET.LinearGeometry.4.0.dll</HintPath>
    </Reference>
    <Reference Include="Bentley.CifNET.Geometry.4.0">
      <Private>false</Private>
      <HintPath>$(ORD)\Cif\Bentley.CifNET.Geometry.4.0.dll</HintPath>
    </Reference>
    <Reference Include="Bentley.CifNET.SDK.4.0">
      <Private>false</Private>
      <HintPath>$(ORD)\Cif\Bentley.CifNET.SDK.4.0.dll</HintPath>
    </Reference>
    <Reference Include="Bentley.CifNET.SDK.Edit.4.0">
      <Private>false</Private>
      <HintPath>$(ORD)\Cif\Bentley.CifNET.SDK.Edit.4.0.dll</HintPath>
    </Reference>
    <Reference Include="Bentley.CifNET.Formatting.4.0">
      <Private>false</Private>
      <HintPath>$(ORD)\Cif\Bentley.CifNET.Formatting.4.0.dll</HintPath>
    </Reference>
    <Reference Include="Bentley.CifNET.Model.4.0">
      <Private>false</Private>
      <HintPath>$(ORD)\Cif\Bentley.CifNET.Model.4.0.dll</HintPath>
    </Reference>
    <Reference Include="Bentley.DgnDisplayNet">
      <Private>false</Private>
      <HintPath>$(ORD)\Bentley.DgnDisplayNet.dll</HintPath>
    </Reference>
    <Reference Include="Bentley.DgnPlatformNET">
      <Private>false</Private>
      <HintPath>$(ORD)\Bentley.DgnPlatformNET.dll</HintPath>
    </Reference>
    <Reference Include="Bentley.GeometryNET">
      <Private>false</Private>
      <HintPath>$(ORD)\Bentley.GeometryNET.dll</HintPath>
    </Reference>
    <Reference Include="Bentley.GeometryNET.Structs">
      <Private>false</Private>
      <HintPath>$(ORD)\Bentley.GeometryNET.Structs.dll</HintPath>
    </Reference>
    <Reference Include="Bentley.General.1.0">
      <Private>false</Private>
      <HintPath>$(ORD)\Assemblies\ECFramework\Bentley.General.1.0.dll</HintPath>
    </Reference>
    <Reference Include="Bentley.MicroStation.Interfaces.1.0">
      <Private>false</Private>
      <HintPath>$(ORD)\Assemblies\Bentley.MicroStation.Interfaces.1.0.dll</HintPath>
    </Reference>
    <Reference Include="Bentley.Platform">
      <Private>false</Private>
      <HintPath>$(ORD)\Assemblies\ECFramework\Bentley.Platform.dll</HintPath>
    </Reference>
    <Reference Include="Bentley.TerrainModelNET">
      <Private>false</Private>
      <HintPath>$(ORD)\Assemblies\Bentley.TerrainModelNET.dll</HintPath>
    </Reference>
    <Reference Include="Bentley.ECObjects3">
      <Private>false</Private>
      <HintPath>$(ORD)\Assemblies\ECFramework\Bentley.ECObjects3.dll</HintPath>
    </Reference>
    <Reference Include="Bentley.MicroStation">
      <Private>false</Private>
      <HintPath>$(ORD)\Assemblies\Bentley.MicroStation.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
    <Reference Include="ustation">
      <Private>false</Private>
      <HintPath>$(ORD)\ustation.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Examples\CorridorItemsComplexAlignmentCreator.cs" />
    <Compile Include="Examples\CorridorItemsFeatureDefinitionSet.cs" />
    <Compile Include="Examples\CorridorItemsProfileCreator.cs" />
    <Compile Include="Examples\CorridorItemsCorridorCreator.cs" />
    <Compile Include="Examples\HorizontalCurbReturns.cs" />
    <Compile Include="Examples\VerticalComplexAlignmentCreator.cs" />
    <Compile Include="Examples\VerticalParabolaCreator.cs" />
    <Compile Include="Examples\VerticalAlignmentCreator.cs" />
    <Compile Include="Examples\PIAlignmentCreator.cs" />
    <Compile Include="Examples\ComplexAlignmentCreator.cs" />
    <Compile Include="Examples\SpiralCreator.cs" />
    <Compile Include="Examples\ArcCreator.cs" />
    <Compile Include="Examples\HorizontalAlignmentCreator.cs" />
    <Compile Include="Examples\XSCutPointReporter.cs" />
    <Compile Include="Examples\QQChecker.cs" />
    <Compile Include="Examples\TerrainReporter.cs" />
    <Compile Include="Utility\DataDisplayHelper.cs" />
    <Compile Include="Utility\FeatureDefinitionHelper.cs" />
    <Compile Include="Utility\FeatureForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Utility\FeatureForm.Designer.cs">
      <DependentUpon>FeatureForm.cs</DependentUpon>
    </Compile>
    <Compile Include="Utility\PIForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Utility\PIForm.Designer.cs">
      <DependentUpon>PIForm.cs</DependentUpon>
    </Compile>
    <Compile Include="Utility\ProfileForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Utility\ProfileForm.Designer.cs">
      <DependentUpon>ProfileForm.cs</DependentUpon>
    </Compile>
    <Compile Include="Utility\XSCutPointForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Utility\XSCutPointForm.Designer.cs">
      <DependentUpon>XSCutPointForm.cs</DependentUpon>
    </Compile>
    <Compile Include="Utility\GeometryHelper.cs" />
    <Compile Include="Examples\HorizontalAlignmentReporter.cs" />
    <Compile Include="Examples\CorridorReporter.cs" />
    <Compile Include="Examples\PickAlignmentTool.cs" />
    <Compile Include="Utility\ReportResultsForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Utility\ReportResultsForm.Designer.cs">
      <DependentUpon>ReportResultsForm.cs</DependentUpon>
    </Compile>
    <Compile Include="Keyin.cs" />
    <Compile Include="ManagedSDKExample.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Examples\VerticalAlignmentReporter.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="CommandTable.xml">
      <LogicalName>CommandTable.xml</LogicalName>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Utility\FeatureForm.resx">
      <DependentUpon>FeatureForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Utility\PIForm.resx">
      <DependentUpon>PIForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Utility\ProfileForm.resx">
      <DependentUpon>ProfileForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Utility\ReportResultsForm.resx">
      <DependentUpon>ReportResultsForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Utility\XSCutPointForm.resx">
      <DependentUpon>XSCutPointForm.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>